.\" (c) Copyright 2019 Bartosz Mierzynski
.\" see man-pages(7) for more information about formatting
.TH HR 1 2019-05-14 GitHub "hr User Manual"
.SH NAME
hr \- horizontal bar for your terminal
.SH SYNOPSIS
.B hr
[\fISTRING\fR]...
.SH DESCRIPTION
.B hr
outputs lines of characters specified by command-line arguments repeatedly until end of line
.SH AUTHOR
Written by Bartosz Mierzynski
.SH SEE ALSO
echo(1), printf(1), seq(1)
